package main

import (
	"fmt"
	"strings"
)

// goName converts an Anchor IDL identifier (typically lowerCamelCase
// for fields, UpperCamelCase for types) to a Go-style identifier
// with an uppercase initial letter. It does not otherwise rewrite
// the name, so IDL names that are not valid Go identifiers pass
// through and produce a compiler error at generation time rather
// than silently losing information.
func goName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// goPrimitive maps an IDL primitive type name to its Go equivalent.
// pubkey and publicKey both map to solana.PublicKey (Anchor IDLs
// produced by different compiler versions use either spelling).
// u128 and i128 map to [16]byte: Go lacks a native 128-bit integer
// and routing every access through *big.Int would violate the
// project's "no big.Int in hot paths" principle.
func goPrimitive(p string) (string, error) {
	switch p {
	case "u8":
		return "uint8", nil
	case "u16":
		return "uint16", nil
	case "u32":
		return "uint32", nil
	case "u64":
		return "uint64", nil
	case "u128":
		return "[16]byte", nil
	case "i8":
		return "int8", nil
	case "i16":
		return "int16", nil
	case "i32":
		return "int32", nil
	case "i64":
		return "int64", nil
	case "i128":
		return "[16]byte", nil
	case "bool":
		return "bool", nil
	case "string":
		return "string", nil
	case "bytes":
		return "[]byte", nil
	case "pubkey", "publicKey":
		return "solana.PublicKey", nil
	}
	return "", fmt.Errorf("unknown primitive type %q", p)
}

// goTypeFor renders an IDL TypeRef as a Go type expression.
// Composite types (vec, option, array, defined) recurse into
// their inner type. Defined references pass through goName so
// the referenced type name matches the one the types generator
// produced.
func goTypeFor(t TypeRef) (string, error) {
	switch {
	case t.Primitive != "":
		return goPrimitive(t.Primitive)
	case t.Vec != nil:
		inner, err := goTypeFor(*t.Vec)
		if err != nil {
			return "", err
		}
		return "[]" + inner, nil
	case t.Option != nil:
		inner, err := goTypeFor(*t.Option)
		if err != nil {
			return "", err
		}
		return "*" + inner, nil
	case t.Array != nil:
		inner, err := goTypeFor(*t.Array.Element)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("[%d]%s", t.Array.Length, inner), nil
	case t.Defined != "":
		return goName(t.Defined), nil
	}
	return "", fmt.Errorf("empty type reference")
}

// fileHeader returns the canonical code-generator banner that
// every generated file starts with. It contains the exact phrase
// Go's documentation-tool toolchain uses to mark files as
// generated ("DO NOT EDIT").
func fileHeader() string {
	return "// Code generated by anchoridl-gen; DO NOT EDIT.\n\n"
}
