// Code generated by anchoridl-gen; DO NOT EDIT.

package counter

// CounterDiscriminator is the 8-byte Anchor discriminator prefix for a
// Counter account, used to distinguish it from other accounts owned by
// the same program.
var CounterDiscriminator = [8]byte{0xff, 0xb0, 0x04, 0xf5, 0xbc, 0xfd, 0x7c, 0x19}

// MatchAccount returns the name of the account type whose
// discriminator matches the first 8 bytes of data, or an empty
// string if no known type matches. It does not verify the
// remainder of data; callers should decode further with the
// matched type's Unmarshal function (generated in a follow-up).
func MatchAccount(data []byte) string {
	if len(data) < 8 {
		return ""
	}
	var head [8]byte
	copy(head[:], data[:8])
	switch head {
	case CounterDiscriminator:
		return "Counter"
	}
	return ""
}
