// Code generated by anchor-idl-gen; DO NOT EDIT.

package counter

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
)

// CounterDiscriminator is the 8-byte Anchor discriminator prefix for a
// Counter account, used to distinguish it from other accounts owned by
// the same program.
var CounterDiscriminator = [8]byte{0xff, 0xb0, 0x04, 0xf5, 0xbc, 0xfd, 0x7c, 0x19}

// MatchAccount returns the name of the account type whose
// discriminator matches the first 8 bytes of data, or an empty
// string if no known type matches. It does not verify the
// remainder of data; use UnmarshalXxx to fully decode the
// account body.
func MatchAccount(data []byte) string {
	if len(data) < 8 {
		return ""
	}
	var head [8]byte
	copy(head[:], data[:8])
	switch head {
	case CounterDiscriminator:
		return "Counter"
	}
	return ""
}

// UnmarshalCounter decodes the on-chain Counter account bytes: the leading
// 8-byte discriminator is verified and the remainder is Borsh-decoded
// into a new Counter value.
func UnmarshalCounter(data []byte) (*Counter, error) {
	if len(data) < 8 {
		return nil, fmt.Errorf("Counter: short header (%d bytes)", len(data))
	}
	if !bytes.Equal(data[:8], CounterDiscriminator[:]) {
		return nil, fmt.Errorf("Counter: discriminator mismatch")
	}
	r := bytes.NewReader(data[8:])
	out := &Counter{}
	if err := decodeCounter(r, out); err != nil {
		return nil, err
	}
	return out, nil
}

// decodeCounter Borsh-decodes the fields of Counter from r.
func decodeCounter(r *bytes.Reader, out *Counter) error {
	{
		v, err := readU64(r)
		if err != nil {
			return err
		}
		out.Count = v
	}
	if _, err := io.ReadFull(r, out.Authority[:]); err != nil {
		return err
	}
	{
		n, err := readU32(r)
		if err != nil {
			return err
		}
		out.History = make([]uint64, n)
		for i := uint32(0); i < n; i++ {
			{
				v, err := readU64(r)
				if err != nil {
					return err
				}
				out.History[i] = v
			}
		}
	}
	{
		b, err := r.ReadByte()
		if err != nil {
			return err
		}
		out.Bump = b
	}
	for i := 0; i < 32; i++ {
		{
			b, err := r.ReadByte()
			if err != nil {
				return err
			}
			out.Label[i] = b
		}
	}
	{
		tag, err := r.ReadByte()
		if err != nil {
			return err
		}
		if tag == 1 {
			var _tmp uint64
			{
				v, err := readU64(r)
				if err != nil {
					return err
				}
				_tmp = v
			}
			out.Last = &_tmp
		} else if tag != 0 {
			return fmt.Errorf("borsh option: invalid tag %d", tag)
		}
	}
	{
		b, err := r.ReadByte()
		if err != nil {
			return err
		}
		out.Direction = Direction(b)
	}
	return nil
}

// readU16 reads a little-endian uint16 from r.
func readU16(r *bytes.Reader) (uint16, error) {
	var b [2]byte
	if _, err := io.ReadFull(r, b[:]); err != nil {
		return 0, err
	}
	return binary.LittleEndian.Uint16(b[:]), nil
}

// readU32 reads a little-endian uint32 from r.
func readU32(r *bytes.Reader) (uint32, error) {
	var b [4]byte
	if _, err := io.ReadFull(r, b[:]); err != nil {
		return 0, err
	}
	return binary.LittleEndian.Uint32(b[:]), nil
}

// readU64 reads a little-endian uint64 from r.
func readU64(r *bytes.Reader) (uint64, error) {
	var b [8]byte
	if _, err := io.ReadFull(r, b[:]); err != nil {
		return 0, err
	}
	return binary.LittleEndian.Uint64(b[:]), nil
}

// readString reads a Borsh length-prefixed UTF-8 string from r.
func readString(r *bytes.Reader) (string, error) {
	b, err := readBytes(r)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// readBytes reads a Borsh length-prefixed byte slice from r.
func readBytes(r *bytes.Reader) ([]byte, error) {
	n, err := readU32(r)
	if err != nil {
		return nil, err
	}
	out := make([]byte, n)
	if _, err := io.ReadFull(r, out); err != nil {
		return nil, err
	}
	return out, nil
}
