// Code generated by anchoridl-gen; DO NOT EDIT.

package counter

import "fmt"

// ProgramError is an Anchor program error code declared in the IDL.
type ProgramError struct {
	Code int
	Name string
	Msg  string
}

// Error implements the error interface.
func (e *ProgramError) Error() string {
	return fmt.Sprintf("%s (code %d): %s", e.Name, e.Code, e.Msg)
}

// ErrOverflow corresponds to the Anchor error code 6000.
var ErrOverflow = &ProgramError{Code: 6000, Name: "Overflow", Msg: "Counter overflow"}

// ErrorByCode returns the ProgramError matching the given numeric
// code, or nil if the code is not declared in the program's IDL.
func ErrorByCode(code int) *ProgramError {
	switch code {
	case 6000:
		return ErrOverflow
	}
	return nil
}
