// Code generated by anchor-idl-gen; DO NOT EDIT.

package counter

import (
	"bytes"
	"encoding/binary"

	solana "github.com/cielu/solana-go"
)

// ProgramAddress is the on-chain address of the counter program
// as recorded in the IDL.
var ProgramAddress = solana.MustPublicKeyFromBase58("Cnt1111111111111111111111111111111111111111")

// IncrementDiscriminator is the 8-byte Anchor discriminator for the
// Increment instruction.
var IncrementDiscriminator = [8]byte{0x0b, 0x12, 0x68, 0x09, 0x68, 0xae, 0x3b, 0x21}

// IncrementInstruction builds the Increment instruction.
type IncrementInstruction struct {
	Counter   solana.PublicKey // writable
	Authority solana.PublicKey // signer
	Amount    uint64
}

// ProgramID returns the program address for the Increment instruction.
func (ix *IncrementInstruction) ProgramID() solana.PublicKey { return ProgramAddress }

// Accounts returns account metas for the Increment instruction in
// the positional order the program expects. Optional accounts
// that are nil are skipped.
func (ix *IncrementInstruction) Accounts() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 2)
	metas = append(metas, solana.NewAccountMeta(ix.Counter, false, true))
	metas = append(metas, solana.NewAccountMeta(ix.Authority, true, false))
	return metas
}

// Data returns the Borsh-encoded instruction payload: 8-byte
// discriminator followed by the instruction arguments.
func (ix *IncrementInstruction) Data() ([]byte, error) {
	var buf bytes.Buffer
	buf.Write(IncrementDiscriminator[:])
	{
		var _b [8]byte
		binary.LittleEndian.PutUint64(_b[:], ix.Amount)
		buf.Write(_b[:])
	}
	return buf.Bytes(), nil
}
