// Code generated by anchoridl-gen; DO NOT EDIT.

package counter

import "github.com/cielu/solana-go"

// Counter is generated from the Anchor IDL.
type Counter struct {
	Count     uint64
	Authority solana.PublicKey
	History   []uint64
	Bump      uint8
	Label     [32]uint8
	Last      *uint64
	Direction Direction
}

// Direction is generated from the Anchor IDL.
type Direction uint8

const (
	DirectionUp   Direction = 0
	DirectionDown Direction = 1
)
